# Generated by Django 4.2.5 on 2024-07-22 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gaka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gaka_name", models.CharField(max_length=200, verbose_name="画家名")),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "男性"), (2, "女性")], verbose_name="性別"
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="生年月日")),
                ("nationality", models.CharField(max_length=100, verbose_name="国籍")),
                (
                    "awards",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="受賞"
                    ),
                ),
                (
                    "artistic_style",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="作風"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_name", models.CharField(max_length=200, verbose_name="作品名")),
                ("year_of_creation", models.DateField(verbose_name="制作年")),
                (
                    "techniques_used",
                    models.CharField(max_length=200, verbose_name="使用技法"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="主題"
                    ),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="所蔵場所"
                    ),
                ),
                ("image", models.ImageField(upload_to="artworks/")),
                (
                    "average_r",
                    models.FloatField(editable=False, null=True, verbose_name="平均R"),
                ),
                (
                    "average_g",
                    models.FloatField(editable=False, null=True, verbose_name="平均G"),
                ),
                (
                    "average_b",
                    models.FloatField(editable=False, null=True, verbose_name="平均B"),
                ),
                (
                    "brightness",
                    models.FloatField(editable=False, null=True, verbose_name="明度"),
                ),
                (
                    "saturation",
                    models.FloatField(editable=False, null=True, verbose_name="彩度"),
                ),
                (
                    "gaka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to="gaka.gaka",
                    ),
                ),
            ],
        ),
    ]
