# Generated by Django 4.2.5 on 2024-07-23 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gaka", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gaka",
            name="artistic_style",
        ),
    ]
