# Generated by Django 4.2.5 on 2024-07-23 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gaka", "0002_remove_gaka_artistic_style"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gaka",
            name="awards",
        ),
    ]
