# Generated by Django 4.2.5 on 2024-07-23 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gaka", "0003_remove_gaka_awards"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="current_location",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="subject",
        ),
    ]
