# Generated by Django 4.2.5 on 2024-07-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaka", "0004_remove_artwork_current_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="techniques_used",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="使用技法"
            ),
        ),
    ]
