# Generated by Django 4.2.5 on 2024-07-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaka", "0005_alter_artwork_techniques_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="year_of_creation",
            field=models.DateField(blank=True, null=True, verbose_name="制作年"),
        ),
    ]
