# Generated by Django 4.2.5 on 2024-07-24 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gaka", "0006_alter_artwork_year_of_creation"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="artwork",
            table="artworks",
        ),
        migrations.AlterModelTable(
            name="gaka",
            table="gaka",
        ),
    ]
