# Generated by Django 4.2.5 on 2024-07-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaka", "0007_alter_artwork_table_alter_gaka_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="emotion",
            field=models.CharField(blank=True, null=True, verbose_name="感情"),
        ),
    ]
